version: '3'

services:
  vstsdockerbuild.webapp:
    image: vstsdockerbuild.webapp
    build:
      context: .
      dockerfile: src/VstsDockerBuild.WebApp/Dockerfile

  vstsdockerbuild.pongservice:
    image: vstsdockerbuild.pongservice
    build:
      context: .
      dockerfile: src/VstsDockerBuild.PongService/Dockerfile

