version: '3'

services:
  vstsdockerbuild.webapp:
    image: vstsdockerbuild.webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PongService=http://vstsdockerbuild.pongservice
      - BLOWUPINTEGRATION
    ports:
      - "80"
    depends_on:
      - vstsdockerbuild.pongservice
    logging:
      driver: "none"

  vstsdockerbuild.pongservice:
    image: vstsdockerbuild.pongservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB=mongodb://mongo/Ping-Events
    ports:
      - "80"
    logging:
      driver: "none"
    depends_on:
      - mongo
  
  vstsdockerbuild.integrationtests:
    image: vstsdockerbuild.integrationtests
    build:
      context: .
      dockerfile: tests/VstsDockerBuild.IntegrationTests/Dockerfile
    entrypoint: dotnet test
    environment:
      - PongService=http://vstsdockerbuild.pongservice
      - WebApp=http://vstsdockerbuild.webapp
      - MongoDB=mongodb://mongo/Ping-Events
    depends_on:
      - vstsdockerbuild.pongservice
      - vstsdockerbuild.webapp
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017"
    
